# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'loginVeRDCN.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QWidget, QComboBox, QVBoxLayout, QStackedWidget)

class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)

        self.centralwidget = QWidget(MainWindow)
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        # Fondo de la ventana principal
        self.frame = QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(161, 214, 226);")
        self.horizontalLayout.addWidget(self.frame)

        # Contenedor central
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setGeometry(QRect(348, 175, 350, 400))
        self.frame_2.setStyleSheet("""
            background-color: rgb(241, 241, 242);
            border-radius: 20px;
            box-shadow: 10px 10px 30px rgba(0, 0, 0, 0.1);
        """)

        # Título central
        self.label_3 = QLabel(self.frame)
        self.label_3.setGeometry(QRect(250, 62, 500, 50))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(40)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3.setText("INICIAR SESIÓN")

        # Etiqueta de correo electrónico
        self.label = QLabel(self.frame_2)
        self.label.setGeometry(QRect(50, 50, 250, 25))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setText("Correo electrónico")

        # Campo de texto para el correo
        self.line_edit_email_login = QLineEdit(self.frame_2)
        self.line_edit_email_login.setGeometry(QRect(50, 90, 250, 35))
        self.line_edit_email_login.setObjectName(u"line_edit_email_login")
        self.line_edit_email_login.setStyleSheet("""
            border: 2px solid rgb(150, 150, 150);
            border-radius: 10px;
            padding-left: 10px;
            font-size: 14px;
        """)

        # Etiqueta de contraseña
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setGeometry(QRect(50, 150, 250, 25))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2.setText("Contraseña")

        # Campo de texto para la contraseña
        self.line_edit_password_login = QLineEdit(self.frame_2)
        self.line_edit_password_login.setGeometry(QRect(50, 190, 250, 35))
        self.line_edit_password_login.setObjectName(u"line_edit_password_login")
        self.line_edit_password_login.setStyleSheet("""
            border: 2px solid rgb(150, 150, 150);
            border-radius: 10px;
            padding-left: 10px;
            font-size: 14px;
        """)
        self.line_edit_password_login.setEchoMode(QLineEdit.EchoMode.Password)

        # Botón de iniciar sesión
        self.push_button_log_in_login = QPushButton(self.frame_2)
        self.push_button_log_in_login.setGeometry(QRect(100, 240, 150, 35))
        self.push_button_log_in_login.setText("Iniciar sesión")
        self.push_button_log_in_login.setObjectName(u"push_button_log_in_login")
        self.push_button_log_in_login.setStyleSheet("""
            background-color: rgb(61, 174, 233);
            color: white;
            font-size: 14px;
            border-radius: 15px;
        """)

        # Botón de registrarse
        self.push_button_sign_up_login = QPushButton(self.frame_2)
        self.push_button_sign_up_login.setGeometry(QRect(100, 285, 150, 35))
        self.push_button_sign_up_login.setText("Registrarse")
        self.push_button_sign_up_login.setObjectName(u"push_button_sign_up_login")
        self.push_button_sign_up_login.setStyleSheet("""
            background-color: rgb(85, 170, 127);
            color: white;
            font-size: 14px;
            border-radius: 15px;
        """)

        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setWindowTitle("Login")

class Ui_SignupWindow(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1000, 700)

        # Layout principal
        self.horizontalLayout = QHBoxLayout(Dialog)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        # Marco principal con color de fondo
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: rgb(161, 214, 226);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        # Marco interior centrado
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(325, 100, 350, 500))
        self.frame_2.setStyleSheet(u"background-color: rgb(241, 241, 242);"
                                   "border-radius: 15px;")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)

        # Título principal
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 30, 500, 50))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(40)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setText(QCoreApplication.translate("Dialog", u"REGISTRARSE", None))

        # Campos de texto y etiquetas
        self.add_label(self.frame_2, u"label", QRect(50, 20, 250, 25), "Nombre")
        self.line_edit_name_signup = self.add_line_edit(self.frame_2, QRect(50, 50, 250, 25))

        self.add_label(self.frame_2, u"label_2", QRect(50, 90, 250, 25), "Correo electrónico")
        self.line_edit_email_signup = self.add_line_edit(self.frame_2, QRect(50, 120, 250, 25))

        self.add_label(self.frame_2, u"label_4", QRect(50, 160, 250, 25), "Domicilio")
        self.line_edit_domicile_signup = self.add_line_edit(self.frame_2, QRect(50, 190, 250, 25))

        self.add_label(self.frame_2, u"label_5", QRect(50, 230, 250, 25), "Área")
        self.combo_box_area_signup = self.add_combo_box(self.frame_2, QRect(50, 260, 250, 25))

        self.add_label(self.frame_2, u"label_6", QRect(50, 310, 250, 25), "Contraseña")
        self.line_edit_password_signup = self.add_line_edit(self.frame_2, QRect(50, 340, 250, 25))

        # Botones
        self.push_button_sign_up_signup = self.add_button(self.frame_2, QRect(100, 400, 150, 30), "Registrarse")
        self.push_button_log_in_signup = self.add_button(self.frame_2, QRect(100, 450, 150, 30), "Iniciar sesión")

        # Añadir el marco principal al layout
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def add_label(self, parent, name, geometry, text):
        label = QLabel(parent)
        label.setObjectName(name)
        label.setGeometry(geometry)
        label.setAlignment(Qt.AlignCenter)
        label.setText(QCoreApplication.translate("Dialog", text, None))
        return label

    def add_line_edit(self, parent, geometry):
        line_edit = QLineEdit(parent)
        line_edit.setGeometry(geometry)
        line_edit.setStyleSheet(u"padding: 5px; border: 1px solid #b3b3b3; border-radius: 5px;")
        return line_edit

    def add_combo_box(self, parent, geometry):
        combo_box = QComboBox(parent)
        combo_box.setGeometry(geometry)
        combo_box.setStyleSheet(u"padding: 5px; border: 1px solid #b3b3b3; border-radius: 5px;")
        combo_box.addItems([
            "Ventas", "Atención al cliente", "Marketing", "Caja y Facturación",
            "Servicio técnico", "Inventario y logística", "Administración", "Seguridad"
        ])
        return combo_box

    def add_button(self, parent, geometry, text):
        button = QPushButton(parent)
        button.setGeometry(geometry)
        button.setText(QCoreApplication.translate("Dialog", text, None))
        button.setStyleSheet(u"background-color: rgb(161, 214, 226); padding: 10px;"
                             "border: none; border-radius: 10px;")
        return button

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Registro", None))

class Ui_MenuWindow(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1000, 700)

        # Layout horizontal principal
        self.horizontalLayout = QHBoxLayout(Dialog)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        # Frame principal con color de fondo
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: rgb(161, 214, 226);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)

        # Etiqueta para el título principal "MENÚ"
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 62, 500, 50))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(40)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)

        # Frame para el botón de productos
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(100, 200, 350, 350))
        self.frame_2.setStyleSheet(u"background-color: rgb(241, 241, 242); border-radius: 15px;")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)

        # Botón de productos con ícono
        self.push_button_product_menu = QPushButton(self.frame_2)
        self.push_button_product_menu.setObjectName(u"push_button_product_menu")
        self.push_button_product_menu.setGeometry(QRect(25, 25, 300, 300))
        self.push_button_product_menu.setStyleSheet(u"background-color: transparent; border: none;")
        icon = QIcon()
        icon.addFile(u"images/product.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.push_button_product_menu.setIcon(icon)
        self.push_button_product_menu.setIconSize(QSize(200, 200))

        # Frame para el botón de empleados
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(550, 200, 350, 350))
        self.frame_3.setStyleSheet(u"background-color: rgb(241, 241, 242); border-radius: 15px;")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)

        # Botón de empleados con ícono
        self.push_button_employee_menu = QPushButton(self.frame_3)
        self.push_button_employee_menu.setObjectName(u"push_button_employee_menu")
        self.push_button_employee_menu.setGeometry(QRect(25, 25, 300, 300))
        self.push_button_employee_menu.setStyleSheet(u"background-color: transparent; border: none;")
        icon1 = QIcon()
        icon1.addFile(u"images/employee.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.push_button_employee_menu.setIcon(icon1)
        self.push_button_employee_menu.setIconSize(QSize(200, 200))

        # Botón de cerrar sesión
        self.push_button_log_out_menu = QPushButton(self.frame)
        self.push_button_log_out_menu.setObjectName(u"push_button_log_out_menu")
        self.push_button_log_out_menu.setGeometry(QRect(400, 600, 200, 50))
        self.push_button_log_out_menu.setStyleSheet(u"""
            background-color: rgb(241, 241, 242); 
            padding: 10px; 
            border: none; 
            border-radius: 15px;
        """)

        # Añadir frame principal al layout
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Menú", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"MEN\u00da", None))
        self.push_button_product_menu.setText("")
        self.push_button_employee_menu.setText("")
        self.push_button_log_out_menu.setText(QCoreApplication.translate("Dialog", u"CERRAR SESIÓN", None))

class Ui_ProductWindow(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1000, 700)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: rgb(161, 214, 226)")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 62, 500, 50))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(40)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(50, 150, 900, 500))
        self.frame_2.setStyleSheet(u"background-color: rgb(241, 241, 242)")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 250, 500))
        self.frame_3.setStyleSheet(u"background-color: rgb(133, 176, 186)")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.push_button_create_menu_product = QPushButton(self.frame_3)
        self.push_button_create_menu_product.setObjectName(u"push_button_create_menu_product")
        self.push_button_create_menu_product.setEnabled(True)
        self.push_button_create_menu_product.setMaximumSize(QSize(16777215, 50))
        font1 = QFont()
        font1.setPointSize(16)
        self.push_button_create_menu_product.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_create_menu_product)

        self.push_button_read_menu_product = QPushButton(self.frame_3)
        self.push_button_read_menu_product.setObjectName(u"push_button_read_menu_product")
        self.push_button_read_menu_product.setMaximumSize(QSize(16777215, 50))
        self.push_button_read_menu_product.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_read_menu_product)

        self.push_button_update_menu_product = QPushButton(self.frame_3)
        self.push_button_update_menu_product.setObjectName(u"push_button_update_menu_product")
        self.push_button_update_menu_product.setMaximumSize(QSize(16777215, 50))
        self.push_button_update_menu_product.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_update_menu_product)

        self.push_button_delete_menu_product = QPushButton(self.frame_3)
        self.push_button_delete_menu_product.setObjectName(u"push_button_delete_menu_product")
        self.push_button_delete_menu_product.setMaximumSize(QSize(16777215, 50))
        self.push_button_delete_menu_product.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_delete_menu_product)

        self.push_button_back_menu = QPushButton(self.frame_3)
        self.push_button_back_menu.setObjectName(u"push_button_back_menu")
        self.push_button_back_menu.setMaximumSize(QSize(16777215, 50))
        self.push_button_back_menu.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_back_menu)

        self.stackedWidget = QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(250, 0, 650, 500))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(241, 241, 242)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 40, 250, 16))
        font2 = QFont()
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_price_create_product = QLineEdit(self.page)
        self.line_edit_price_create_product.setObjectName(u"line_edit_price_create_product")
        self.line_edit_price_create_product.setGeometry(QRect(350, 140, 250, 25))
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 100, 250, 25))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combo_box_category_create_product = QComboBox(self.page)
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.addItem("")
        self.combo_box_category_create_product.setObjectName(u"combo_box_category_create_product")
        self.combo_box_category_create_product.setGeometry(QRect(50, 220, 250, 25))
        self.line_edit_name_create_product = QLineEdit(self.page)
        self.line_edit_name_create_product.setObjectName(u"line_edit_name_create_product")
        self.line_edit_name_create_product.setGeometry(QRect(50, 140, 250, 25))
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(350, 100, 250, 25))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 180, 250, 25))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 180, 250, 25))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_quantity_create_product = QLineEdit(self.page)
        self.line_edit_quantity_create_product.setObjectName(u"line_edit_quantity_create_product")
        self.line_edit_quantity_create_product.setGeometry(QRect(350, 220, 250, 25))
        self.push_button_create_product = QPushButton(self.page)
        self.push_button_create_product.setObjectName(u"push_button_create_product")
        self.push_button_create_product.setGeometry(QRect(250, 440, 150, 25))
        self.line_edit_model_create_product = QLineEdit(self.page)
        self.line_edit_model_create_product.setObjectName(u"line_edit_model_create_product")
        self.line_edit_model_create_product.setGeometry(QRect(50, 300, 250, 25))
        self.label_13 = QLabel(self.page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 260, 250, 25))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.push_button_read_product = QPushButton(self.page_2)
        self.push_button_read_product.setObjectName(u"push_button_read_product")
        self.push_button_read_product.setGeometry(QRect(250, 440, 150, 25))
        self.line_edit_id_read_product = QLineEdit(self.page_2)
        self.line_edit_id_read_product.setObjectName(u"line_edit_id_read_product")
        self.line_edit_id_read_product.setGeometry(QRect(320, 100, 50, 25))
        self.label_22 = QLabel(self.page_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(270, 100, 50, 25))
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(200, 40, 250, 16))
        self.label_23.setFont(font2)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.page_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(350, 230, 250, 25))
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(50, 150, 250, 25))
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.page_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(350, 150, 250, 25))
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.page_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(50, 230, 250, 25))
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_28 = QLabel(self.page_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(50, 310, 250, 25))
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_4 = QFrame(self.page_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(50, 190, 250, 25))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_name_update_product = QLabel(self.frame_4)
        self.label_name_update_product.setObjectName(u"label_name_update_product")
        self.label_name_update_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_6 = QFrame(self.page_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(50, 270, 250, 25))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.label_category_update_product = QLabel(self.frame_6)
        self.label_category_update_product.setObjectName(u"label_category_update_product")
        self.label_category_update_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_7 = QFrame(self.page_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(50, 350, 250, 25))
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.label_model_update_product = QLabel(self.frame_7)
        self.label_model_update_product.setObjectName(u"label_model_update_product")
        self.label_model_update_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_8 = QFrame(self.page_2)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(350, 190, 250, 25))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.label_price_update_product = QLabel(self.frame_8)
        self.label_price_update_product.setObjectName(u"label_price_update_product")
        self.label_price_update_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_9 = QFrame(self.page_2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(350, 270, 250, 25))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.label_quantity_update_product = QLabel(self.frame_9)
        self.label_quantity_update_product.setObjectName(u"label_quantity_update_product")
        self.label_quantity_update_product.setGeometry(QRect(0, 0, 250, 25))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.line_edit_quantity_update_product = QLineEdit(self.page_3)
        self.line_edit_quantity_update_product.setObjectName(u"line_edit_quantity_update_product")
        self.line_edit_quantity_update_product.setGeometry(QRect(350, 270, 250, 25))
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 150, 250, 25))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_name_update_product = QLineEdit(self.page_3)
        self.line_edit_name_update_product.setObjectName(u"line_edit_name_update_product")
        self.line_edit_name_update_product.setGeometry(QRect(50, 190, 250, 25))
        self.line_edit_price_update_product = QLineEdit(self.page_3)
        self.line_edit_price_update_product.setObjectName(u"line_edit_price_update_product")
        self.line_edit_price_update_product.setGeometry(QRect(350, 190, 250, 25))
        self.line_edit_model_update_product = QLineEdit(self.page_3)
        self.line_edit_model_update_product.setObjectName(u"line_edit_model_update_product")
        self.line_edit_model_update_product.setGeometry(QRect(50, 350, 250, 25))
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 230, 250, 25))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 310, 250, 25))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.push_button_update_product = QPushButton(self.page_3)
        self.push_button_update_product.setObjectName(u"push_button_update_product")
        self.push_button_update_product.setGeometry(QRect(250, 440, 150, 25))
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(350, 230, 250, 25))
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(200, 40, 250, 16))
        self.label_19.setFont(font2)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(350, 150, 250, 25))
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combo_box_category_update_product = QComboBox(self.page_3)
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.addItem("")
        self.combo_box_category_update_product.setObjectName(u"combo_box_category_update_product")
        self.combo_box_category_update_product.setGeometry(QRect(50, 270, 250, 25))
        self.line_edit_id_update_product = QLineEdit(self.page_3)
        self.line_edit_id_update_product.setObjectName(u"line_edit_id_update_product")
        self.line_edit_id_update_product.setGeometry(QRect(320, 100, 50, 25))
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(270, 100, 50, 25))
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.line_edit_id_delete_product = QLineEdit(self.page_4)
        self.line_edit_id_delete_product.setObjectName(u"line_edit_id_delete_product")
        self.line_edit_id_delete_product.setGeometry(QRect(320, 100, 50, 25))
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(50, 150, 250, 25))
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 100, 50, 25))
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 310, 250, 25))
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_10 = QFrame(self.page_4)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(50, 270, 250, 25))
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.label_category_delete_product = QLabel(self.frame_10)
        self.label_category_delete_product.setObjectName(u"label_category_delete_product")
        self.label_category_delete_product.setGeometry(QRect(0, 0, 250, 25))
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(350, 150, 250, 25))
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_11 = QFrame(self.page_4)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(50, 350, 250, 25))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.label_model_delete_product = QLabel(self.frame_11)
        self.label_model_delete_product.setObjectName(u"label_model_delete_product")
        self.label_model_delete_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_12 = QFrame(self.page_4)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(350, 190, 250, 25))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.label_price_delete_product = QLabel(self.frame_12)
        self.label_price_delete_product.setObjectName(u"label_price_delete_product")
        self.label_price_delete_product.setGeometry(QRect(0, 0, 250, 25))
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(50, 230, 250, 25))
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(350, 230, 250, 25))
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.push_button_delete_product = QPushButton(self.page_4)
        self.push_button_delete_product.setObjectName(u"push_button_delete_product")
        self.push_button_delete_product.setGeometry(QRect(250, 440, 150, 25))
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(200, 40, 250, 16))
        self.label_35.setFont(font2)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_13 = QFrame(self.page_4)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(50, 190, 250, 25))
        self.frame_13.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.label_name_delete_product = QLabel(self.frame_13)
        self.label_name_delete_product.setObjectName(u"label_name_delete_product")
        self.label_name_delete_product.setGeometry(QRect(0, 0, 250, 25))
        self.frame_14 = QFrame(self.page_4)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(350, 270, 250, 25))
        self.frame_14.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Shadow.Raised)
        self.label_quantity_delete = QLabel(self.frame_14)
        self.label_quantity_delete.setObjectName(u"label_quantity_delete")
        self.label_quantity_delete.setGeometry(QRect(0, 0, 250, 25))
        self.stackedWidget.addWidget(self.page_4)

        self.verticalLayout.addWidget(self.frame)


        self.retranslateUi(Dialog)

        self.stackedWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"PRODUCTO", None))
        self.push_button_create_menu_product.setText(QCoreApplication.translate("Dialog", u"Crear", None))
        self.push_button_read_menu_product.setText(QCoreApplication.translate("Dialog", u"Consultar", None))
        self.push_button_update_menu_product.setText(QCoreApplication.translate("Dialog", u"Modificar", None))
        self.push_button_delete_menu_product.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.push_button_back_menu.setText(QCoreApplication.translate("Dialog", u"Regresar", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"CREAR PRODUCTO", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.combo_box_category_create_product.setItemText(0, QCoreApplication.translate("Dialog", u"Procesador", None))
        self.combo_box_category_create_product.setItemText(1, QCoreApplication.translate("Dialog", u"Tarjeta gr\u00e1fica", None))
        self.combo_box_category_create_product.setItemText(2, QCoreApplication.translate("Dialog", u"RAM", None))
        self.combo_box_category_create_product.setItemText(3, QCoreApplication.translate("Dialog", u"Almacenamiento", None))
        self.combo_box_category_create_product.setItemText(4, QCoreApplication.translate("Dialog", u"Tarjeta madre", None))
        self.combo_box_category_create_product.setItemText(5, QCoreApplication.translate("Dialog", u"Perif\u00e9ricos", None))

        self.label_5.setText(QCoreApplication.translate("Dialog", u"Precio", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Categor\u00eda", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Cantidad", None))
        self.push_button_create_product.setText(QCoreApplication.translate("Dialog", u"Crear", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Modelo", None))
        self.push_button_read_product.setText(QCoreApplication.translate("Dialog", u"Consultar", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"CONSULTAR PRODUCTO", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Cantidad", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"Precio", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Categor\u00eda", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Modelo", None))
        self.label_name_update_product.setText("")
        self.label_category_update_product.setText("")
        self.label_model_update_product.setText("")
        self.label_price_update_product.setText("")
        self.label_quantity_update_product.setText("")
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Categor\u00eda", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Modelo", None))
        self.push_button_update_product.setText(QCoreApplication.translate("Dialog", u"Modificar", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Cantidad", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"MODIFICAR PRODUCTO", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Precio", None))
        self.combo_box_category_update_product.setItemText(0, QCoreApplication.translate("Dialog", u"Procesador", None))
        self.combo_box_category_update_product.setItemText(1, QCoreApplication.translate("Dialog", u"Tarjeta gr\u00e1fica", None))
        self.combo_box_category_update_product.setItemText(2, QCoreApplication.translate("Dialog", u"RAM", None))
        self.combo_box_category_update_product.setItemText(3, QCoreApplication.translate("Dialog", u"Almacenamiento", None))
        self.combo_box_category_update_product.setItemText(4, QCoreApplication.translate("Dialog", u"Tarjeta madre", None))
        self.combo_box_category_update_product.setItemText(5, QCoreApplication.translate("Dialog", u"Perif\u00e9ricos", None))

        self.label_21.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Modelo", None))
        self.label_category_delete_product.setText("")
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Precio", None))
        self.label_model_delete_product.setText("")
        self.label_price_delete_product.setText("")
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Categor\u00eda", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Cantidad", None))
        self.push_button_delete_product.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"ELIMINAR PRODUCTO", None))
        self.label_name_delete_product.setText("")
        self.label_quantity_delete.setText("")
    # retranslateUi

class Ui_EmployeeWindow(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1000, 700)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: rgb(161, 214, 226)")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 62, 500, 50))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(40)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(50, 150, 900, 500))
        self.frame_2.setStyleSheet(u"background-color: rgb(241, 241, 242)")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 250, 500))
        self.frame_3.setStyleSheet(u"background-color: rgb(133, 176, 186)")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.push_button_create_menu_employee = QPushButton(self.frame_3)
        self.push_button_create_menu_employee.setObjectName(u"push_button_create_menu_employee")
        self.push_button_create_menu_employee.setEnabled(True)
        self.push_button_create_menu_employee.setMaximumSize(QSize(16777215, 50))
        font1 = QFont()
        font1.setPointSize(16)
        self.push_button_create_menu_employee.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_create_menu_employee)

        self.push_button_read_menu_employee = QPushButton(self.frame_3)
        self.push_button_read_menu_employee.setObjectName(u"push_button_read_menu_employee")
        self.push_button_read_menu_employee.setMaximumSize(QSize(16777215, 50))
        self.push_button_read_menu_employee.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_read_menu_employee)

        self.push_button_update_menu_employee = QPushButton(self.frame_3)
        self.push_button_update_menu_employee.setObjectName(u"push_button_update_menu_employee")
        self.push_button_update_menu_employee.setMaximumSize(QSize(16777215, 50))
        self.push_button_update_menu_employee.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_update_menu_employee)

        self.push_button_delete_menu_employee = QPushButton(self.frame_3)
        self.push_button_delete_menu_employee.setObjectName(u"push_button_delete_menu_employee")
        self.push_button_delete_menu_employee.setMaximumSize(QSize(16777215, 50))
        self.push_button_delete_menu_employee.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_delete_menu_employee)

        self.push_button_back_menu = QPushButton(self.frame_3)
        self.push_button_back_menu.setObjectName(u"push_button_back_menu")
        self.push_button_back_menu.setMaximumSize(QSize(16777215, 50))
        self.push_button_back_menu.setFont(font1)

        self.verticalLayout_2.addWidget(self.push_button_back_menu)

        self.stackedWidget = QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(250, 0, 650, 500))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(241, 241, 242)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 40, 250, 16))
        font2 = QFont()
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_email_create_employee = QLineEdit(self.page)
        self.line_edit_email_create_employee.setObjectName(u"line_edit_email_create_employee")
        self.line_edit_email_create_employee.setGeometry(QRect(350, 140, 250, 25))
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 100, 250, 25))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combo_box_area_create_employee = QComboBox(self.page)
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.addItem("")
        self.combo_box_area_create_employee.setObjectName(u"combo_box_area_create_employee")
        self.combo_box_area_create_employee.setGeometry(QRect(50, 220, 250, 25))
        self.line_edit_name_create_employee = QLineEdit(self.page)
        self.line_edit_name_create_employee.setObjectName(u"line_edit_name_create_employee")
        self.line_edit_name_create_employee.setGeometry(QRect(50, 140, 250, 25))
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(350, 100, 250, 25))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 180, 250, 25))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 180, 250, 25))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_domicile_create_employee = QLineEdit(self.page)
        self.line_edit_domicile_create_employee.setObjectName(u"line_edit_domicile_create_employee")
        self.line_edit_domicile_create_employee.setGeometry(QRect(350, 220, 250, 25))
        self.push_button_create_employee = QPushButton(self.page)
        self.push_button_create_employee.setObjectName(u"push_button_create_employee")
        self.push_button_create_employee.setGeometry(QRect(250, 440, 150, 25))
        self.line_edit_salary_create_employee = QLineEdit(self.page)
        self.line_edit_salary_create_employee.setObjectName(u"line_edit_salary_create_employee")
        self.line_edit_salary_create_employee.setGeometry(QRect(50, 300, 250, 25))
        self.label_13 = QLabel(self.page)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 260, 250, 25))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.push_button_read_employee = QPushButton(self.page_2)
        self.push_button_read_employee.setObjectName(u"push_button_read_employee")
        self.push_button_read_employee.setGeometry(QRect(250, 440, 150, 25))
        self.line_edit_id_read_employee = QLineEdit(self.page_2)
        self.line_edit_id_read_employee.setObjectName(u"line_edit_id_read_employee")
        self.line_edit_id_read_employee.setGeometry(QRect(320, 100, 50, 25))
        self.label_22 = QLabel(self.page_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(270, 100, 50, 25))
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(200, 40, 250, 16))
        self.label_23.setFont(font2)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.page_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(350, 230, 250, 25))
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(50, 150, 250, 25))
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.page_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(350, 150, 250, 25))
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.page_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(50, 230, 250, 25))
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_28 = QLabel(self.page_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(50, 310, 250, 25))
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_4 = QFrame(self.page_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(50, 190, 250, 25))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_name_read_employee = QLabel(self.frame_4)
        self.label_name_read_employee.setObjectName(u"label_name_read_employee")
        self.label_name_read_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_6 = QFrame(self.page_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(50, 270, 250, 25))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.label_area_read_employee = QLabel(self.frame_6)
        self.label_area_read_employee.setObjectName(u"label_area_read_employee")
        self.label_area_read_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_7 = QFrame(self.page_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(50, 350, 250, 25))
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.label_salary_read_employee = QLabel(self.frame_7)
        self.label_salary_read_employee.setObjectName(u"label_salary_read_employee")
        self.label_salary_read_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_8 = QFrame(self.page_2)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(350, 190, 250, 25))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.label_email_read_employee = QLabel(self.frame_8)
        self.label_email_read_employee.setObjectName(u"label_email_read_employee")
        self.label_email_read_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_9 = QFrame(self.page_2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(350, 270, 250, 25))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.label_domicile_read_employee = QLabel(self.frame_9)
        self.label_domicile_read_employee.setObjectName(u"label_domicile_read_employee")
        self.label_domicile_read_employee.setGeometry(QRect(0, 0, 250, 25))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.line_edit_domicile_update_employee = QLineEdit(self.page_3)
        self.line_edit_domicile_update_employee.setObjectName(u"line_edit_domicile_update_employee")
        self.line_edit_domicile_update_employee.setGeometry(QRect(350, 270, 250, 25))
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 150, 250, 25))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_name_update_employee = QLineEdit(self.page_3)
        self.line_edit_name_update_employee.setObjectName(u"line_edit_name_update_employee")
        self.line_edit_name_update_employee.setGeometry(QRect(50, 190, 250, 25))
        self.line_edit_email_update_employee = QLineEdit(self.page_3)
        self.line_edit_email_update_employee.setObjectName(u"line_edit_email_update_employee")
        self.line_edit_email_update_employee.setGeometry(QRect(350, 190, 250, 25))
        self.line_edit_salary_update_employee = QLineEdit(self.page_3)
        self.line_edit_salary_update_employee.setObjectName(u"line_edit_salary_update_employee")
        self.line_edit_salary_update_employee.setGeometry(QRect(50, 350, 250, 25))
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 230, 250, 25))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 310, 250, 25))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.push_button_update_employee = QPushButton(self.page_3)
        self.push_button_update_employee.setObjectName(u"push_button_update_employee")
        self.push_button_update_employee.setGeometry(QRect(250, 440, 150, 25))
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(350, 230, 250, 25))
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(200, 40, 250, 16))
        self.label_19.setFont(font2)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(350, 150, 250, 25))
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_edit_id_update_employee = QLineEdit(self.page_3)
        self.line_edit_id_update_employee.setObjectName(u"line_edit_id_update_employee")
        self.line_edit_id_update_employee.setGeometry(QRect(320, 100, 50, 25))
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(270, 100, 50, 25))
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combo_box_area_update_employee = QComboBox(self.page_3)
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.addItem("")
        self.combo_box_area_update_employee.setObjectName(u"combo_box_area_update_employee")
        self.combo_box_area_update_employee.setGeometry(QRect(50, 270, 250, 25))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.line_edit_id_delete_employee = QLineEdit(self.page_4)
        self.line_edit_id_delete_employee.setObjectName(u"line_edit_id_delete_employee")
        self.line_edit_id_delete_employee.setGeometry(QRect(320, 100, 50, 25))
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(50, 150, 250, 25))
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 100, 50, 25))
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 310, 250, 25))
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_10 = QFrame(self.page_4)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(50, 270, 250, 25))
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.label_area_delete_employee = QLabel(self.frame_10)
        self.label_area_delete_employee.setObjectName(u"label_area_delete_employee")
        self.label_area_delete_employee.setGeometry(QRect(0, 0, 250, 25))
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(350, 150, 250, 25))
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_11 = QFrame(self.page_4)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(50, 350, 250, 25))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.label_salary_delete_employee = QLabel(self.frame_11)
        self.label_salary_delete_employee.setObjectName(u"label_salary_delete_employee")
        self.label_salary_delete_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_12 = QFrame(self.page_4)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(350, 190, 250, 25))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.label_email_delete_employee = QLabel(self.frame_12)
        self.label_email_delete_employee.setObjectName(u"label_email_delete_employee")
        self.label_email_delete_employee.setGeometry(QRect(0, 0, 250, 25))
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(50, 230, 250, 25))
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(350, 230, 250, 25))
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.push_button_delete_employee = QPushButton(self.page_4)
        self.push_button_delete_employee.setObjectName(u"push_button_delete_employee")
        self.push_button_delete_employee.setGeometry(QRect(250, 440, 150, 25))
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(200, 40, 250, 16))
        self.label_35.setFont(font2)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_13 = QFrame(self.page_4)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(50, 190, 250, 25))
        self.frame_13.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.label_name_delete_employee = QLabel(self.frame_13)
        self.label_name_delete_employee.setObjectName(u"label_name_delete_employee")
        self.label_name_delete_employee.setGeometry(QRect(0, 0, 250, 25))
        self.frame_14 = QFrame(self.page_4)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(350, 270, 250, 25))
        self.frame_14.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Shadow.Raised)
        self.label_domicile_delete_employee = QLabel(self.frame_14)
        self.label_domicile_delete_employee.setObjectName(u"label_domicile_delete_employee")
        self.label_domicile_delete_employee.setGeometry(QRect(0, 0, 250, 25))
        self.stackedWidget.addWidget(self.page_4)

        self.verticalLayout.addWidget(self.frame)


        self.retranslateUi(Dialog)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"EMPLEADOS", None))
        self.push_button_create_menu_employee.setText(QCoreApplication.translate("Dialog", u"Crear", None))
        self.push_button_read_menu_employee.setText(QCoreApplication.translate("Dialog", u"Consultar", None))
        self.push_button_update_menu_employee.setText(QCoreApplication.translate("Dialog", u"Modificar", None))
        self.push_button_delete_menu_employee.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.push_button_back_menu.setText(QCoreApplication.translate("Dialog", u"Regresar", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"CREAR USUARIO", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.combo_box_area_create_employee.setItemText(0, QCoreApplication.translate("Dialog", u"Ventas", None))
        self.combo_box_area_create_employee.setItemText(1, QCoreApplication.translate("Dialog", u"Atenci\u00f3n al cliente", None))
        self.combo_box_area_create_employee.setItemText(2, QCoreApplication.translate("Dialog", u"Marketing", None))
        self.combo_box_area_create_employee.setItemText(3, QCoreApplication.translate("Dialog", u"Caja y facturaci\u00f3n", None))
        self.combo_box_area_create_employee.setItemText(4, QCoreApplication.translate("Dialog", u"Servicio t\u00e9cnico", None))
        self.combo_box_area_create_employee.setItemText(5, QCoreApplication.translate("Dialog", u"Inventario y log\u00edstica", None))
        self.combo_box_area_create_employee.setItemText(6, QCoreApplication.translate("Dialog", u"Administraci\u00f3n y finanzas", None))
        self.combo_box_area_create_employee.setItemText(7, QCoreApplication.translate("Dialog", u"Seguridad", None))

        self.label_5.setText(QCoreApplication.translate("Dialog", u"Correo electr\u00f3nico", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"\u00c1rea", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Domicilio", None))
        self.push_button_create_employee.setText(QCoreApplication.translate("Dialog", u"Crear", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Salario", None))
        self.push_button_read_employee.setText(QCoreApplication.translate("Dialog", u"Consultar", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"CONSULTAR PRODUCTO", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Domicilio", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"Correo electr\u00f3nico", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"\u00c1rea", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Salario", None))
        self.label_name_read_employee.setText("")
        self.label_area_read_employee.setText("")
        self.label_salary_read_employee.setText("")
        self.label_email_read_employee.setText("")
        self.label_domicile_read_employee.setText("")
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"\u00c1rea", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Salario", None))
        self.push_button_update_employee.setText(QCoreApplication.translate("Dialog", u"Modificar", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Domicilio", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"MODIFICAR USUARIO", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Correo electr\u00f3nico", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.combo_box_area_update_employee.setItemText(0, QCoreApplication.translate("Dialog", u"Ventas", None))
        self.combo_box_area_update_employee.setItemText(1, QCoreApplication.translate("Dialog", u"Atenci\u00f3n al cliente", None))
        self.combo_box_area_update_employee.setItemText(2, QCoreApplication.translate("Dialog", u"Marketing", None))
        self.combo_box_area_update_employee.setItemText(3, QCoreApplication.translate("Dialog", u"Caja y facturaci\u00f3n", None))
        self.combo_box_area_update_employee.setItemText(4, QCoreApplication.translate("Dialog", u"Servicio t\u00e9cnico", None))
        self.combo_box_area_update_employee.setItemText(5, QCoreApplication.translate("Dialog", u"Inventario y log\u00edstica", None))
        self.combo_box_area_update_employee.setItemText(6, QCoreApplication.translate("Dialog", u"Administraci\u00f3n y finanzas", None))
        self.combo_box_area_update_employee.setItemText(7, QCoreApplication.translate("Dialog", u"Seguridad", None))

        self.label_29.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Salario", None))
        self.label_area_delete_employee.setText("")
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Correo electr\u00f3nico", None))
        self.label_salary_delete_employee.setText("")
        self.label_email_delete_employee.setText("")
        self.label_33.setText(QCoreApplication.translate("Dialog", u"\u00c1rea", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Domicilio", None))
        self.push_button_delete_employee.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"ELIMINAR USUARIO", None))
        self.label_name_delete_employee.setText("")
        self.label_domicile_delete_employee.setText("")
    # retranslateUi

